name: build
on:
    # run on push but only for the develop and release branches
    push:
        branches:
            - develop
            - release
    # run for every pull request
    pull_request: {}
jobs:
    main:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: [12]
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
